# Generated by Django 6.1.2 on 2026-10-06 13:23

import django.db.models.deletion
import geospatial.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('KML', 'KML'), ('SHAPEFILE', 'SHAPEFILE')], max_length=20)),
                ('file', models.FileField(upload_to=geospatial.models.upload_path)),
                ('status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('COMPLETED_WITH_WARNINGS', 'COMPLETED_WITH_WARNINGS'), ('FAILED', 'FAILED')], default='PROCESSING', max_length=30)),
                ('original_crs', models.CharField(blank=True, max_length=100)),
                ('measurement_crs', models.CharField(blank=True, max_length=100)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_index', models.PositiveIntegerField()),
                ('layer', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry_type', models.CharField(blank=True, max_length=30, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('measurement_type', models.CharField(blank=True, max_length=10, null=True)),
                ('measurement_value', models.FloatField(blank=True, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('measurement_status', models.CharField(choices=[('SUPPORTED', 'SUPPORTED'), ('NOT_REQUIRED', 'NOT_REQUIRED'), ('UNSUPPORTED', 'UNSUPPORTED'), ('INVALID', 'INVALID')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='geospatial.uploadedfile')),
            ],
            options={
                'ordering': ['source_index'],
                'indexes': [models.Index(fields=['uploaded_file', 'measurement_status'], name='geospatial__uploade_09857a_idx')],
                'constraints': [models.UniqueConstraint(fields=('uploaded_file', 'source_index'), name='unique_feature_index_per_file')],
            },
        ),
    ]
